### ISSUE TITLE
如何改变dark模式下加粗文字的显示？比如更换一种颜色

### ISSUE THREAD

**Issue by wwjCMP** [ZekunC/Obsidian-Typora-Vue-Theme#11]
在亮模式下，这种加粗显示是对比明显。但是在暗模式下，这种加粗显示则并不明显。所以想问一下有没有css片段可以实现将加粗文字以一种和其他文字对比度更高的颜色来显示。比如Border主题中的这种颜色。
![Snipaste_2023-04-10_00-10-31](https://user-images.githubusercontent.com/32979859/230783853-e358c074-b1e3-4614-8866-d45b84170ac4.png)

**Comment by ZekunC** [comment]
可以。使用下面这个代码片段，第一个属性改粗细的程度，默认的加粗是600；第二个属性可以指定加粗的颜色。
```css
.theme-dark{
        --bold-weight: 600;
	--bold-color: #FFFFFF;
}
```
