### ISSUE TITLE
如何更改行间距

### ISSUE THREAD

**Issue by weikefan123** [ZekunC/Obsidian-Typora-Vue-Theme#8]
麻烦您了 自己弄了半天代码一直不生效 请问下怎么调整行间距，中文状态下觉得有点挤

**Comment by ZekunC** [comment]
你好，css中默认为：
```css
body{
    /* Line heights */
  --line-height-normal: 1.5;
  --line-height-tight: 1.3;	
}
```
第一个是正常情况下的，第二个是需要紧一些的时候用。你改第一个就行。
