### ISSUE TITLE
如何将图片更改为居中显示

### ISSUE THREAD

**Issue by Kohirus** [ZekunC/Obsidian-Typora-Vue-Theme#9]
我更希望图片可以居中显示，而非停靠左侧。这应该如何修改？

**Comment by ZekunC** [comment]
如果你想让所有图片默认居中，那么添加如下的代码片段
```css
img{
	display:block;
	margin: 0px auto;
}

```

如果你仅想让指定图像居中，添加如下代码片段，并使用 `![center](./image.png)` 或 `![[image.png | center]]` 。
```css
img[alt*="center"]{
	display:block;
	margin: 0px auto;
}
```
